package service;

public enum MediaScanStatus {
    ADDED,
    ADDED_DUPLICATE_CONTENT,
    UPDATED,
    UPDATED_DUPLICATE_CONTENT,
    UNCHANGED,
    WOULD_ADD,
    WOULD_ADD_DUPLICATE_CONTENT,
    WOULD_UPDATE,
    WOULD_UPDATE_DUPLICATE_CONTENT,
    FAILED
}
