package service;

public enum ReadyPageBatchOutcome {
    CREATED_WITHOUT_RENAME,
    CREATED_AND_RENAMED,
    CREATED_RENAME_FAILED_NEEDS_REVIEW,
    SKIPPED_NO_LONGER_READY,
    SKIPPED_ALREADY_ASSIGNED,
    SKIPPED_MEDIA_MISSING,
    FAILED
}
