package service;

public enum SceneReviewSaveStatus {
    CREATED,
    CREATED_AND_RENAMED,
    CREATED_RENAME_FAILED_NEEDS_REVIEW,
    UPDATED,
    UPDATED_AND_RENAMED,
    UPDATED_RENAME_FAILED_NEEDS_REVIEW,
    VALIDATION_FAILED,
    ASSIGNMENT_CONFLICT,
    FAILED
}
